# Generated by Django 5.2.17 on 2026-09-25 12:59

import django.core.validators
import django.db.models.deletion
import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('certification_id', models.AutoField(primary_key=True, serialize=False, verbose_name='資格ID')),
                ('name', models.CharField(max_length=255, verbose_name='資格名')),
                ('acquired_on', models.CharField(max_length=32, verbose_name='取得日')),
                ('org', models.CharField(max_length=255, verbose_name='発行団体')),
                ('sort_order', models.PositiveIntegerField(verbose_name='表示順')),
            ],
            options={
                'verbose_name': '資格',
                'verbose_name_plural': '資格',
                'db_table': 'certifications',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='レベル')),
                ('portfolio_label', models.CharField(max_length=100, verbose_name='ポートフォリオ凡例')),
                ('resume_label', models.CharField(max_length=100, verbose_name='職務経歴書レベル文言')),
            ],
            options={
                'verbose_name': '習熟度レベル',
                'verbose_name_plural': '習熟度レベル',
                'db_table': 'levels',
                'ordering': ['-level'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(default=portfolio.models.generate_project_id, editable=False, max_length=64, primary_key=True, serialize=False, verbose_name='案件ID')),
                ('name', models.CharField(max_length=255, verbose_name='案件名')),
                ('start_year_month', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='年月は YYYY-MM 形式で入力してください。', regex='^\\d{4}-(0[1-9]|1[0-2])$')], verbose_name='開始年月')),
                ('end_year_month', models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator(message='年月は YYYY-MM 形式で入力してください。', regex='^\\d{4}-(0[1-9]|1[0-2])$')], verbose_name='終了年月')),
            ],
            options={
                'verbose_name': '案件実績',
                'verbose_name_plural': '案件実績',
                'db_table': 'projects',
                'ordering': ['start_year_month'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('work_id', models.AutoField(primary_key=True, serialize=False, verbose_name='実績ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('desc_ja', models.TextField(verbose_name='説明文（日本語）')),
                ('desc_en', models.TextField(blank=True, default='', verbose_name='説明文（英語）')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='使用技術タグ')),
                ('thumbnail', models.CharField(blank=True, default='', max_length=255, verbose_name='サムネイル')),
                ('github_url', models.URLField(blank=True, default='', max_length=255, verbose_name='GitHub URL')),
                ('live_url', models.URLField(blank=True, default='', max_length=255, verbose_name='公開 URL')),
                ('sort_order', models.PositiveIntegerField(verbose_name='表示順')),
            ],
            options={
                'verbose_name': '実績',
                'verbose_name_plural': '実績',
                'db_table': 'works',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.CharField(max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='skill_id は半角英小文字・数字・ハイフンで入力してください。', regex='^[a-z0-9-]+$')], verbose_name='スキル項目ID')),
                ('category', models.CharField(max_length=64, verbose_name='種類')),
                ('name', models.CharField(max_length=128, verbose_name='表示名')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='補足')),
                ('sort_order', models.PositiveIntegerField(verbose_name='表示順')),
                ('level', models.ForeignKey(db_column='level', on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='portfolio.level', verbose_name='習熟度')),
            ],
            options={
                'verbose_name': 'スキル項目',
                'verbose_name_plural': 'スキル項目',
                'db_table': 'skills',
                'ordering': ['category', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSkill',
            fields=[
                ('pk', models.CompositePrimaryKey('project', 'skill', blank=True, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(blank=True, default='', max_length=64, verbose_name='バージョン')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='project_skills', to='portfolio.project', verbose_name='案件')),
                ('skill', models.ForeignKey(db_column='skill_id', on_delete=django.db.models.deletion.PROTECT, related_name='project_skills', to='portfolio.skill', verbose_name='スキル項目')),
            ],
            options={
                'verbose_name': '案件使用スキル',
                'verbose_name_plural': '案件使用スキル',
                'db_table': 'project_skills',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(related_name='projects', through='portfolio.ProjectSkill', to='portfolio.skill'),
        ),
    ]
