# Generated by Django 5.2.17 on 2026-09-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_insert_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('site_info_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False, verbose_name='サイト情報ID')),
                ('name', models.CharField(max_length=255, verbose_name='氏名')),
                ('typing_titles', models.JSONField(default=list, verbose_name='肩書き')),
                ('catchphrase', models.CharField(max_length=255, verbose_name='キャッチコピー')),
                ('intro', models.TextField(verbose_name='自己紹介文')),
                ('birth_date', models.DateField(verbose_name='生年月日')),
                ('job', models.CharField(max_length=255, verbose_name='職業')),
                ('education', models.CharField(max_length=255, verbose_name='学歴')),
                ('location', models.CharField(max_length=255, verbose_name='居住地')),
                ('hobby', models.CharField(max_length=255, verbose_name='趣味')),
                ('github_url', models.URLField(max_length=255, verbose_name='GitHub URL')),
                ('contact_message', models.TextField(verbose_name='Contact の案内文')),
                ('contact_form_url', models.URLField(max_length=1024, verbose_name='問い合わせフォーム URL')),
                ('copyright_start_year', models.PositiveSmallIntegerField(verbose_name='著作権の開始年')),
            ],
            options={
                'verbose_name': 'サイト情報',
                'verbose_name_plural': 'サイト情報',
                'db_table': 'site_info',
            },
        ),
    ]
