# Generated by Django 5.2.17 on 2026-09-27 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_skill_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['acquired_on', 'certification_id'], 'verbose_name': '資格', 'verbose_name_plural': '資格'},
        ),
    ]
