# Generated by Django 5.2.17 on 2026-10-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_merge_ecs_fargate_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skillsheet',
            fields=[
                ('skillsheet_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False, verbose_name='職務経歴書ID')),
                ('body', models.TextField(verbose_name='本文')),
                ('updated_at', models.DateTimeField(verbose_name='最終更新日時')),
            ],
            options={
                'verbose_name': '職務経歴書',
                'verbose_name_plural': '職務経歴書',
                'db_table': 'skillsheet',
            },
        ),
    ]
