# Generated by Django 5.2.17 on 2026-10-10 14:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_skillsheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False, verbose_name='会社ID')),
                ('name', models.CharField(max_length=255, verbose_name='会社名')),
                ('department', models.CharField(blank=True, default='', max_length=255, verbose_name='部署名')),
                ('employment_type', models.CharField(blank=True, default='', max_length=64, verbose_name='雇用・契約形態')),
                ('kind', models.CharField(choices=[('main', '本業'), ('side', '副業')], max_length=8, verbose_name='区分')),
                ('start_year_month', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='年月は YYYY-MM 形式で入力してください。', regex='^\\d{4}-(0[1-9]|1[0-2])$')], verbose_name='在籍開始年月')),
                ('end_year_month', models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator(message='年月は YYYY-MM 形式で入力してください。', regex='^\\d{4}-(0[1-9]|1[0-2])$')], verbose_name='在籍終了年月')),
                ('capital', models.CharField(blank=True, default='', max_length=64, verbose_name='資本金')),
                ('employees', models.CharField(blank=True, default='', max_length=64, verbose_name='従業員数')),
                ('offices', models.CharField(blank=True, default='', max_length=64, verbose_name='拠点数')),
                ('annual_sales', models.CharField(blank=True, default='', max_length=64, verbose_name='年商')),
                ('founded', models.CharField(blank=True, default='', max_length=64, verbose_name='設立')),
            ],
            options={
                'verbose_name': '会社',
                'verbose_name_plural': '会社',
                'db_table': 'companies',
                'ordering': ['kind', '-start_year_month', 'company_id'],
            },
        ),
        migrations.CreateModel(
            name='SkillsheetText',
            fields=[
                ('text_key', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='項目キー')),
                ('body', models.TextField(verbose_name='内容')),
                ('updated_at', models.DateTimeField(verbose_name='最終更新日時')),
            ],
            options={
                'verbose_name': '職務経歴書の文章項目',
                'verbose_name_plural': '職務経歴書の文章項目',
                'db_table': 'skillsheet_texts',
            },
        ),
        migrations.DeleteModel(
            name='Skillsheet',
        ),
        migrations.AddField(
            model_name='project',
            name='environment',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='環境・言語'),
        ),
        migrations.AddField(
            model_name='project',
            name='overview',
            field=models.TextField(blank=True, default='', verbose_name='案件概要'),
        ),
        migrations.AddField(
            model_name='project',
            name='phases',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='担当工程'),
        ),
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.TextField(blank=True, default='', verbose_name='業務内容'),
        ),
        migrations.AddField(
            model_name='project',
            name='team_size',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='体制'),
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='portfolio.company', verbose_name='会社'),
        ),
    ]
