# Generated by Django 5.2.17 on 2026-10-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_environment_one_item_per_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_master',
            field=models.BooleanField(default=False, verbose_name='マスタ項目'),
        ),
    ]
